#database credentials
spring.datasource.url= EXAMPLE
spring.datasource.username= EXAMPLE
spring.datasource.password= EXAMPLE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring.jpa.hibernate.ddl-auto = validate

spring.liquibase.change-log=classpath:/static/db/changelog-master.xml

spring.batch.job.name = createReport
spring.batch.jdbc.initialize-schema=ALWAYS