version: '3'

services:
  spring-app:
    container_name: spring-app
    build:
      context: ./spring/service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      FLASK_APP_URL: http://flask-app:5000
    depends_on:
      - mysql
      - flask-app
    networks:
      - app-network

  flask-app:
    container_name: flask-app
    build:
      context: ./flask/service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://root:rootpassword@mysql:3306/flaskdb
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springdb
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
