package com.example.weatheraggregator.collector.provider.tomorrowio.response;

import java.util.Map;

import static java.util.Map.entry;

public class TIOWeatherCodeMapper {
    private static final Map<Integer, String> weatherCodes = Map.<Integer, String>ofEntries(
            entry(0, "Unknown"),
            entry(1000, "Clear, Sunny"),
            entry(1100, "Mostly Clear"),
            entry(1101, "Partly Cloudy"),
            entry(1102, "Mostly Cloudy"),
            entry(1001, "Cloudy"),
            entry(1103, "Partly Cloudy and Mostly Clear"),
            entry(2100, "Light Fog"),
            entry(2101, "Mostly Clear and Light Fog"),
            entry(2102, "Partly Cloudy and Light Fog"),
            entry(2103, "Mostly Cloudy and Light Fog"),
            entry(2106, "Mostly Clear and Fog"),
            entry(2107, "Partly Cloudy and Fog"),
            entry(2108, "Mostly Cloudy and Fog"),
            entry(2000, "Fog"),
            entry(4204, "Partly Cloudy and Drizzle"),
            entry(4203, "Mostly Clear and Drizzle"),
            entry(4205, "Mostly Cloudy and Drizzle"),
            entry(4000, "Drizzle"),
            entry(4200, "Light Rain"),
            entry(4213, "Mostly Clear and Light Rain"),
            entry(4214, "Partly Cloudy and Light Rain"),
            entry(4215, "Mostly Cloudy and Light Rain"),
            entry(4209, "Mostly Clear and Rain"),
            entry(4208, "Partly Cloudy and Rain"),
            entry(4210, "Mostly Cloudy and Rain"),
            entry(4001, "Rain"),
            entry(4211, "Mostly Clear and Heavy Rain"),
            entry(4202, "Partly Cloudy and Heavy Rain"),
            entry(4212, "Mostly Cloudy and Heavy Rain"),
            entry(4201, "Heavy Rain"),
            entry(5115, "Mostly Clear and Flurries"),
            entry(5116, "Partly Cloudy and Flurries"),
            entry(5117, "Mostly Cloudy and Flurries"),
            entry(5001, "Flurries"),
            entry(5100, "Light Snow"),
            entry(5102, "Mostly Clear and Light Snow"),
            entry(5103, "Partly Cloudy and Light Snow"),
            entry(5104, "Mostly Cloudy and Light Snow"),
            entry(5122, "Drizzle and Light Snow"),
            entry(5105, "Mostly Clear and Snow"),
            entry(5106, "Partly Cloudy and Snow"),
            entry(5107, "Mostly Cloudy and Snow"),
            entry(5000, "Snow"),
            entry(5101, "Heavy Snow"),
            entry(5119, "Mostly Clear and Heavy Snow"),
            entry(5120, "Partly Cloudy and Heavy Snow"),
            entry(5121, "Mostly Cloudy and Heavy Snow"),
            entry(5110, "Drizzle and Snow"),
            entry(5108, "Rain and Snow"),
            entry(5114, "Snow and Freezing Rain"),
            entry(5112, "Snow and Ice Pellets"),
            entry(6000, "Freezing Drizzle"),
            entry(6003, "Mostly Clear and Freezing drizzle"),
            entry(6002, "Partly Cloudy and Freezing drizzle"),
            entry(6004, "Mostly Cloudy and Freezing drizzle"),
            entry(6204, "Drizzle and Freezing Drizzle"),
            entry(6206, "Light Rain and Freezing Drizzle"),
            entry(6205, "Mostly Clear and Light Freezing Rain"),
            entry(6203, "Partly Cloudy and Light Freezing Rain"),
            entry(6209, "Mostly Cloudy and Light Freezing Rain"),
            entry(6200, "Light Freezing Rain"),
            entry(6213, "Mostly Clear and Freezing Rain"),
            entry(6214, "Partly Cloudy and Freezing Rain"),
            entry(6215, "Mostly Cloudy and Freezing Rain"),
            entry(6001, "Freezing Rain"),
            entry(6212, "Drizzle and Freezing Rain"),
            entry(6220, "Light Rain and Freezing Rain"),
            entry(6222, "Rain and Freezing Rain"),
            entry(6207, "Mostly Clear and Heavy Freezing Rain"),
            entry(6202, "Partly Cloudy and Heavy Freezing Rain"),
            entry(6208, "Mostly Cloudy and Heavy Freezing Rain"),
            entry(6201, "Heavy Freezing Rain"),
            entry(7110, "Mostly Clear and Light Ice Pellets"),
            entry(7111, "Partly Cloudy and Light Ice Pellets"),
            entry(7112, "Mostly Cloudy and Light Ice Pellets"),
            entry(7102, "Light Ice Pellets"),
            entry(7108, "Mostly Clear and Ice Pellets"),
            entry(7107, "Partly Cloudy and Ice Pellets"),
            entry(7109, "Mostly Cloudy and Ice Pellets"),
            entry(7000, "Ice Pellets"),
            entry(7105, "Drizzle and Ice Pellets"),
            entry(7106, "Freezing Rain and Ice Pellets"),
            entry(7115, "Light Rain and Ice Pellets"),
            entry(7117, "Rain and Ice Pellets"),
            entry(7103, "Freezing Rain and Heavy Ice Pellets"),
            entry(7113, "Mostly Clear and Heavy Ice Pellets"),
            entry(7114, "Partly Cloudy and Heavy Ice Pellets"),
            entry(7116, "Mostly Cloudy and Heavy Ice Pellets"),
            entry(7101, "Heavy Ice Pellets"),
            entry(8001, "Mostly Clear and Thunderstorm"),
            entry(8003, "Partly Cloudy and Thunderstorm"),
            entry(8002, "Mostly Cloudy and Thunderstorm"),
            entry(8000, "Thunderstorm"),
            entry(10000, "Clear, Sunny"),
            entry(11000, "Mostly Clear"),
            entry(11010, "Partly Cloudy"),
            entry(11020, "Mostly Cloudy"),
            entry(10010, "Cloudy"),
            entry(11030, "Partly Cloudy and Mostly Clear"),
            entry(21000, "Light Fog"),
            entry(21010, "Mostly Clear and Light Fog"),
            entry(21020, "Partly Cloudy and Light Fog"),
            entry(21030, "Mostly Cloudy and Light Fog"),
            entry(21060, "Mostly Clear and Fog"),
            entry(21070, "Partly Cloudy and Fog"),
            entry(21080, "Mostly Cloudy and Fog"),
            entry(20000, "Fog"),
            entry(42040, "Partly Cloudy and Drizzle"),
            entry(42030, "Mostly Clear and Drizzle"),
            entry(42050, "Mostly Cloudy and Drizzle"),
            entry(40000, "Drizzle"),
            entry(42000, "Light Rain"),
            entry(42130, "Mostly Clear and Light Rain"),
            entry(42140, "Partly Cloudy and Light Rain"),
            entry(42150, "Mostly Cloudy and Light Rain"),
            entry(42090, "Mostly Clear and Rain"),
            entry(42080, "Partly Cloudy and Rain"),
            entry(42100, "Mostly Cloudy and Rain"),
            entry(40010, "Rain"),
            entry(42110, "Mostly Clear and Heavy Rain"),
            entry(42020, "Partly Cloudy and Heavy Rain"),
            entry(42120, "Mostly Cloudy and Heavy Rain"),
            entry(42010, "Heavy Rain"),
            entry(51150, "Mostly Clear and Flurries"),
            entry(51160, "Partly Cloudy and Flurries"),
            entry(51170, "Mostly Cloudy and Flurries"),
            entry(50010, "Flurries"),
            entry(51000, "Light Snow"),
            entry(51020, "Mostly Clear and Light Snow"),
            entry(51030, "Partly Cloudy and Light Snow"),
            entry(51040, "Mostly Cloudy and Light Snow"),
            entry(51220, "Drizzle and Light Snow"),
            entry(51050, "Mostly Clear and Snow"),
            entry(51060, "Partly Cloudy and Snow"),
            entry(51070, "Mostly Cloudy and Snow"),
            entry(50000, "Snow"),
            entry(51010, "Heavy Snow"),
            entry(51190, "Mostly Clear and Heavy Snow"),
            entry(51200, "Partly Cloudy and Heavy Snow"),
            entry(51210, "Mostly Cloudy and Heavy Snow"),
            entry(51100, "Drizzle and Snow"),
            entry(51080, "Rain and Snow"),
            entry(51140, "Snow and Freezing Rain"),
            entry(51120, "Snow and Ice Pellets"),
            entry(60000, "Freezing Drizzle"),
            entry(60030, "Mostly Clear and Freezing drizzle"),
            entry(60020, "Partly Cloudy and Freezing drizzle"),
            entry(60040, "Mostly Cloudy and Freezing drizzle"),
            entry(62040, "Drizzle and Freezing Drizzle"),
            entry(62060, "Light Rain and Freezing Drizzle"),
            entry(62050, "Mostly Clear and Light Freezing Rain"),
            entry(62030, "Partly Cloudy and Light Freezing Rain"),
            entry(62090, "Mostly Cloudy and Light Freezing Rain"),
            entry(62000, "Light Freezing Rain"),
            entry(62130, "Mostly Clear and Freezing Rain"),
            entry(62140, "Partly Cloudy and Freezing Rain"),
            entry(62150, "Mostly Cloudy and Freezing Rain"),
            entry(60010, "Freezing Rain"),
            entry(62120, "Drizzle and Freezing Rain"),
            entry(62200, "Light Rain and Freezing Rain"),
            entry(62220, "Rain and Freezing Rain"),
            entry(62070, "Mostly Clear and Heavy Freezing Rain"),
            entry(62020, "Partly Cloudy and Heavy Freezing Rain"),
            entry(62080, "Mostly Cloudy and Heavy Freezing Rain"),
            entry(62010, "Heavy Freezing Rain"),
            entry(71100, "Mostly Clear and Light Ice Pellets"),
            entry(71110, "Partly Cloudy and Light Ice Pellets"),
            entry(71120, "Mostly Cloudy and Light Ice Pellets"),
            entry(71020, "Light Ice Pellets"),
            entry(71080, "Mostly Clear and Ice Pellets"),
            entry(71070, "Partly Cloudy and Ice Pellets"),
            entry(71090, "Mostly Cloudy and Ice Pellets"),
            entry(70000, "Ice Pellets"),
            entry(71050, "Drizzle and Ice Pellets"),
            entry(71060, "Freezing Rain and Ice Pellets"),
            entry(71150, "Light Rain and Ice Pellets"),
            entry(71170, "Rain and Ice Pellets"),
            entry(71030, "Freezing Rain and Heavy Ice Pellets"),
            entry(71130, "Mostly Clear and Heavy Ice Pellets"),
            entry(71140, "Partly Cloudy and Heavy Ice Pellets"),
            entry(71160, "Mostly Cloudy and Heavy Ice Pellets"),
            entry(71010, "Heavy Ice Pellets"),
            entry(80010, "Mostly Clear and Thunderstorm"),
            entry(80030, "Partly Cloudy and Thunderstorm"),
            entry(80020, "Mostly Cloudy and Thunderstorm"),
            entry(80000, "Thunderstorm"),
            entry(10001, "Clear"),
            entry(11001, "Mostly Clear"),
            entry(11011, "Partly Cloudy"),
            entry(11021, "Mostly Cloudy"),
            entry(10011, "Cloudy"),
            entry(11031, "Partly Cloudy and Mostly Clear"),
            entry(21001, "Light Fog"),
            entry(21011, "Mostly Clear and Light Fog"),
            entry(21021, "Partly Cloudy and Light Fog"),
            entry(21031, "Mostly Cloudy and Light Fog"),
            entry(21061, "Mostly Clear and Fog"),
            entry(21071, "Partly Cloudy and Fog"),
            entry(21081, "Mostly Cloudy and Fog"),
            entry(20001, "Fog"),
            entry(42041, "Partly Cloudy and Drizzle"),
            entry(42031, "Mostly Clear and Drizzle"),
            entry(42051, "Mostly Cloudy and Drizzle"),
            entry(40001, "Drizzle"),
            entry(42001, "Light Rain"),
            entry(42131, "Mostly Clear and Light Rain"),
            entry(42141, "Partly Cloudy and Light Rain"),
            entry(42151, "Mostly Cloudy and Light Rain"),
            entry(42091, "Mostly Clear and Rain"),
            entry(42081, "Partly Cloudy and Rain"),
            entry(42101, "Mostly Cloudy and Rain"),
            entry(40011, "Rain"),
            entry(42111, "Mostly Clear and Heavy Rain"),
            entry(42021, "Partly Cloudy and Heavy Rain"),
            entry(42121, "Mostly Cloudy and Heavy Rain"),
            entry(42011, "Heavy Rain"),
            entry(51151, "Mostly Clear and Flurries"),
            entry(51161, "Partly Cloudy and Flurries"),
            entry(51171, "Mostly Cloudy and Flurries"),
            entry(50011, "Flurries"),
            entry(51001, "Light Snow"),
            entry(51021, "Mostly Clear and Light Snow"),
            entry(51031, "Partly Cloudy and Light Snow"),
            entry(51041, "Mostly Cloudy and Light Snow"),
            entry(51221, "Drizzle and Light Snow"),
            entry(51051, "Mostly Clear and Snow"),
            entry(51061, "Partly Cloudy and Snow"),
            entry(51071, "Mostly Cloudy and Snow"),
            entry(50001, "Snow"),
            entry(51011, "Heavy Snow"),
            entry(51191, "Mostly Clear and Heavy Snow"),
            entry(51201, "Partly Cloudy and Heavy Snow"),
            entry(51211, "Mostly Cloudy and Heavy Snow"),
            entry(51101, "Drizzle and Snow"),
            entry(51081, "Rain and Snow"),
            entry(51141, "Snow and Freezing Rain"),
            entry(51121, "Snow and Ice Pellets"),
            entry(60001, "Freezing Drizzle"),
            entry(60031, "Mostly Clear and Freezing drizzle"),
            entry(60021, "Partly Cloudy and Freezing drizzle"),
            entry(60041, "Mostly Cloudy and Freezing drizzle"),
            entry(62041, "Drizzle and Freezing Drizzle"),
            entry(62061, "Light Rain and Freezing Drizzle"),
            entry(62051, "Mostly Clear and Light Freezing Rain"),
            entry(62031, "Partly cloudy and Light Freezing Rain"),
            entry(62091, "Mostly Cloudy and Light Freezing Rain"),
            entry(62001, "Light Freezing Rain"),
            entry(62131, "Mostly Clear and Freezing Rain"),
            entry(62141, "Partly Cloudy and Freezing Rain"),
            entry(62151, "Mostly Cloudy and Freezing Rain"),
            entry(60011, "Freezing Rain"),
            entry(62121, "Drizzle and Freezing Rain"),
            entry(62201, "Light Rain and Freezing Rain"),
            entry(62221, "Rain and Freezing Rain"),
            entry(62071, "Mostly Clear and Heavy Freezing Rain"),
            entry(62021, "Partly Cloudy and Heavy Freezing Rain"),
            entry(62081, "Mostly Cloudy and Heavy Freezing Rain"),
            entry(62011, "Heavy Freezing Rain"),
            entry(71101, "Mostly Clear and Light Ice Pellets"),
            entry(71111, "Partly Cloudy and Light Ice Pellets"),
            entry(71121, "Mostly Cloudy and Light Ice Pellets"),
            entry(71021, "Light Ice Pellets"),
            entry(71081, "Mostly Clear and Ice Pellets"),
            entry(71071, "Partly Cloudy and Ice Pellets"),
            entry(71091, "Mostly Cloudy and Ice Pellets"),
            entry(70001, "Ice Pellets"),
            entry(71051, "Drizzle and Ice Pellets"),
            entry(71061, "Freezing Rain and Ice Pellets"),
            entry(71151, "Light Rain and Ice Pellets"),
            entry(71171, "Rain and Ice Pellets"),
            entry(71031, "Freezing Rain and Heavy Ice Pellets"),
            entry(71131, "Mostly Clear and Heavy Ice Pellets"),
            entry(71141, "Partly Cloudy and Heavy Ice Pellets"),
            entry(71161, "Mostly Cloudy and Heavy Ice Pellets"),
            entry(71011, "Heavy Ice Pellets"),
            entry(80011, "Mostly Clear and Thunderstorm"),
            entry(80031, "Partly Cloudy and Thunderstorm"),
            entry(80021, "Mostly Cloudy and Thunderstorm"),
            entry(80001, "Thunderstorm")
    );

    public static String getCodeDescription(Integer code) {
        return weatherCodes.get(code);
    }
}
